### ISSUE TITLE
Homework Week 10

### ISSUE THREAD

**Issue by ptums** [Ragincajun384/liri-node-app#1]
Hey Andrew, I tried running the liri program but the program requires the keys.js file or the ability to connect to the Twitter API using the authentication keys. Can you set that up and push it up to the repo?

Thanks,

Peter

**Comment by AVanderHoff** [comment]
Fixed it, should be able to run it now.

**Comment by ptums** [comment]
Hey Andrew I got it up and running! Nice job on the homework your code looks really well written. I personally like how you structured the choose commands for the use. Its very clean. Great job :)

**Comment by AVanderHoff** [comment]
Thanks
